name: Check Diff on Push

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    env:
      GRAFANA_CLOUD_PROM_USERNAME: ${{ secrets.GRAFANA_CLOUD_PROM_USERNAME }}
      GRAFANA_CLOUD_PROM_PASSWORD: ${{ secrets.GRAFANA_CLOUD_PROM_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GRAFANA_CLOUD_API_KEY: ${{ secrets.GRAFANA_CLOUD_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install `poetry`
        run: pipx install poetry=="2.0.1"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: "3.12"

      - name: Install dependencies
        run: poetry install

      - name: Generate diff
        id: generate_diff
        run: |
          diff_output=$(poetry run python -m python.diff_pending_and_current_rules)
          echo "$diff_output" > diff.txt
          if [[ -n "$diff_output" ]]; then
            echo "empty=false" >> "$GITHUB_OUTPUT"
          else
            echo "empty=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Post diff as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Current and New Alert Diff
          path: diff.txt
          only_update: ${{ steps.generate_diff.outputs.empty }}
          hide: ${{ steps.generate_diff.outputs.empty }}
          hide_classify: "OUTDATED"
