name: Check Coverage

on:
  schedule:
    - cron: "0 15 * * 1-5" # Runs at 3:00 PM UTC (8:00 AM PT) on weekdays
  workflow_dispatch:

jobs:
  check-coverage:
    runs-on: ubuntu-latest
    env:
      GRAFANA_CLOUD_PROM_USERNAME: ${{ secrets.GRAFANA_CLOUD_PROM_USERNAME }}
      GRAFANA_CLOUD_PROM_PASSWORD: ${{ secrets.GRAFANA_CLOUD_PROM_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GRAFANA_CLOUD_API_KEY: ${{ secrets.GRAFANA_CLOUD_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install `poetry`
        run: pipx install poetry=="2.0.1"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: "3.12"

      - name: Install dependencies
        run: poetry install

      - name: Run coverage check
        run: poetry run python -m python.check_coverage
