
"CPU Usage":
  query: sum by(origin_prometheus, pod) (container_memory_usage_bytes{container="api", origin_prometheus=~"$customer"})
  legend: Usage {{origin_prometheus}} {{pod}}
  unit: bytes

"CPU Limit":
  query: avg by(pod, origin_prometheus) (kube_pod_container_resource_limits{container="api", origin_prometheus=~"$customer", resource="memory"})
  legend: Limit {{origin_prometheus}} {{pod}}
  unit: bytes

"Memory Usage":
  query: sum by(origin_prometheus, pod) (container_memory_usage_bytes{container="api", origin_prometheus=~"$customer"})
  legend: Usage {{origin_prometheus}} {{pod}}
  unit: bytes

"Pod Failure":
  queryA: sum by(pod, origin_prometheus) (increase(kube_pod_container_status_restarts_total{namespace=~".*X.*"}[5m]))
  queryB: sum by(pod, origin_prometheus) (kube_pod_status_phase{namespace=~".*X.*", phase="Failed"})
  queryC: sum by(pod, origin_prometheus) (kube_pod_container_status_waiting_reason{namespace=~".*X.*", reason=~"ImagePullBackOff|ErrImagePull"})
  exprD: $A || $B || $C
  legend: {{origin_prometheus}} {{pod}}

"Unscheduleable Pod"
  query:  
min_over_time(
  sum by(pod, origin_prometheus) (
    kube_pod_status_phase{
      namespace=~".*X.*",
      phase="Pending",
      pod!~".*Y.*"
    }
  )[1h:]
)
