table:
  queryA:
    sum by(origin_prometheus) (increase(api_requests_total{path!~"/internal.*"}[$__range]))
    Format: Table
  queryB:
    sum by(origin_prometheus) (increase(job_completion_total[$__range]))
    Format: Table
  transformationA: Merge
  transformationB: Group by
    time: Ignored
    origin_prometheus: GroupBy
    queryA: Calculate Last
    queryB: Calculate Last
  transformationC: Organize fields by name (rename columns)
